travis:
  secure:
    BINSTAR_TOKEN: H996Yr5RmKsNdnOvbASB5++9plgzER/fKFBPptH4wZ9ElHYajzXWpFcklkaW4xYwCESP2oBDQV2akb2pC90faw+vuzPC0hxfsA8WuzhfFxN8dfv+r6CFZkFl5C9ty8XmKKLwyz8rX7vC9uhBdD6p5/4nKvmtd1r4fzdPM7COboJvTcIfq6TXF7bJCMoH2pHB0ds5nKTN0nhP/9gQroZ9Gqwzs3JUeo0lew5ARTNCQ5P+PJkFYxWa92RP4y7qawAqYa2F0jhIn1TdzCktvmEf3eMKdRy71RhXRPi02qpNHCb69v9dn2HON6NogDJgl5MDinlUcDz2muGihN4LUIHOHB8GAuOC5TaTLHZj5qwy2VbNYfG6ljLYDWLDhz91x3IaIEWSBQHT8wHyMB3p8BYtX0e4SKyIJyDa/cv10tfKaA9Z6+rwKssIobkfMZ8uSHFxtN6dlyzY0h9mKKNZd2GTU65gwhuElbt4OH/5nuhQEt3iPrACuvs4vGZ3NK7N+m9pojP0Mv5QTea+MtPASJNP+cag8e7BoO4qEZMZer6r30b16NasJgZl8kz+L/wGtVeQx/WPNE0OwvpGfW32AMA9We015r0LHWDRmeTSjDPkbJdvFeCtHBip9KHpKFtoDIOuyOs0Z7QLgkRa6/busKqX3HoEOksooFTqgoCSTj8GX7c=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
